name: Manual Build

on: workflow_dispatch
jobs:
  manual-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Create working branch and remove generated files
        run: |
          git branch -D generated || true
          git checkout -b generated
          git rm generated/*
        env:
          CI: true

      - name: Run parser
        run: npm run parse
        env:
          CI: true

      - name: Test parsed lists
        run: npm run test-generated
        env:
          CI: true

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: easylist-for-pi-hole
          path: generated/

      ## FIX: https://github.com/github-actions-x/commit/issues/16
      ## https://github.com/rlespinasse/git-commit-data-action
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.5.0
      - name: Set git author
        run: git config user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}" && git config user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
      ## /FIX

      - name: Commit generated files
        run: |
          git add generated/* || true
          git commit -m 'Easylist generated files' || true

      - name: Check if changed from main
        run: |
          git diff --quiet HEAD main -- generated --exit-code || echo "CHANGED=true" >> $GITHUB_ENV
          echo Changed: ${{ env.CHANGED }}
        env:
          CI: true

      - name: Push generated files
        if: ${{ env.CHANGED == 'true' }}
        run: |
          git push --set-upstream origin generated --force
        env:
          CI: true

      - name: Open Pull Request
        if: ${{ env.CHANGED == 'true' }}
        uses: vsoch/pull-request-action@1.0.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: 'generated'
          PULL_REQUEST_FROM_BRANCH: 'generated'
          PULL_REQUEST_BRANCH: 'main'

      - name: Find Pull Request
        if: ${{ env.CHANGED == 'true' }}
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated

      - name: Merge Pull Request
        if: ${{ env.CHANGED == 'true' }}
        uses: juliangruber/merge-pull-request-action@v1.2.0
        with:
          number: ${{ steps.find-pull-request.outputs.number }}
          method: squash
          github-token: ${{ secrets.GITHUB_TOKEN }}
